### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by manuel-uberti** [purcell/purescript-mode#1]
Hi,

a question more than an issue, but I didn't know where to ask. :)

Is this going to replace https://github.com/dysinger/purescript-mode ?

**Comment by purcell** [comment]
> Is this going to replace https://github.com/dysinger/purescript-mode ?

No - I'm trying to contribute some fixes to it, but upstream is forked from `haskell-mode`, and I already have a clone of that. This setup unfortunately makes contributing via github extremely inconvenient. /cc @dysinger

**Comment by manuel-uberti** [comment]
I see, thanks for the explanation.

**Comment by dysinger** [comment]
Would it be helpful if I deleted the repo? This was originally a hack & haven't maintained it. Sorry everybody

**Comment by purcell** [comment]
> Would it be helpful if I deleted the repo? This was originally a hack & haven't maintained it. Sorry everybody

Well, not immediately - MELPA builds its Emacs `purescript-mode` packages from the code you have there. You could conceivably delete and recreate it as a non-fork, but this would also delete any issues / pull requests. Really not sure what the state of play of this repo is...

Ideal outcome would be that there'd be a `purescript-mode` in the `purescript` github org, and that that repo wouldn't be a fork of the `haskell-mode` repo, so that pull requests etc. work properly. Any thoughts @paf31 / @kRITZCREEK / @justinwoo?

**Comment by purcell** [comment]
My suggested course of action would be to create a new empty `purescript/purescript-mode` repo, and push the commits in this repo to it, then I'd fix up the MELPA recipe to use that instead. At that point you could kill the `dysinger/purescript-mode` repo, and the code could be maintained centrally.

**Comment by justinwoo** [comment]
Seems like something like this would go in `purescript-contrib` if nowhere else, but why not `purcell/purescript-mode`?

**Comment by justinwoo** [comment]
As in, even under `purescript`, it would still have specific maintainers anyway

**Comment by purcell** [comment]
> Seems like something like this would go in `purescript-contrib` if nowhere else, but why not `purcell/purescript-mode`?

`purescript-contrib` would be fine, but I'm not in a position to volunteer to actively maintain this, sorry. I'm not working lots with purescript.

**Comment by kRITZCREEK** [comment]
@purcell Hey, sorry for taking so long to respond. I opened this organization a while ago with the intention of collecting the various PS Emacs packages https://github.com/orgs/purescript-emacs. If you can manage the rerouting in Melpa I'd be happy to move the code with your fixes applied into a repo over there.

**Comment by purcell** [comment]
@kRITZCREEK Great! Can you push a copy of @dysinger's `purescript-mode` there, and make sure it's not a fork of `haskell-mode`? Once done I can point the MELPA recipe at that, and then we can all collaborate there: I can submit my changes as a PR to that repo, for example.

**Comment by dysinger** [comment]
Once completed I will empty out my current repo & leave a link-readme and then leave it like that for a long while.

**Comment by kRITZCREEK** [comment]
@purcell https://github.com/purescript-emacs/purescript-mode, I'll also invite you as a collaborator into the org just in case

**Comment by purcell** [comment]
Great, done now. MELPA should build from the new location.

**Comment by dysinger** [comment]
Are we ready for me to emtpy out the dysinger/purescript-mode repo and leave a README with a link to the new place?

**Comment by purcell** [comment]
> Are we ready for me to empty out the dysinger/purescript-mode repo and leave a README with a link to the new place?

@dysinger Yes please! :-)

**Comment by purcell** [comment]
Likewise, I'll delete this repo now, so this issue will disappear. Thanks everyone.
